---
# tasks file for hadoop_hive
- name: Check if Hive binary is setup at specified location
  ansible.builtin.command: "{{ hive_software_directory }}{{ hive_software_version }}/bin/hive --version"
  ignore_errors: true
  changed_when: false
  register: hive_setup_check

- name: Create Software Directory for Hive at Specified Location
  ansible.builtin.file:
    state: directory
    path: "{{ hive_software_directory }}"
    mode: '0644'
  when: hive_setup_check != 0

- name: Create Hive Workspace
  ansible.builtin.file:
    state: directory
    path: "{{ hive_workspace_directory }}"
    mode: '0644'
  when: hive_setup_check.rc != 0

- name: Ensure .bashrc file exists
  ansible.builtin.copy:
    content: ""
    dest: /home/ubuntu/.bashrc
    force: false
    group: ubuntu
    owner: ubuntu
    mode: o+rwx

- name: Download Hive Software and Extracting it to Specified Location
  ansible.builtin.unarchive:
    src: "{{ hive_software_download_url }}"
    dest: "{{ hive_software_directory }}"
    remote_src: true
  when: hive_setup_check.rc != 0

- name: Make Environmental Variables Permanent after reboot
  ansible.builtin.blockinfile:
    path: /home/ubuntu/.bashrc
    content: |
            export HIVE_HOME={{ hive_software_directory }}{{ hive_software_version }}/
            export PATH={{ hive_software_directory }}{{ hive_software_version }}/bin/:$PATH
