---
# tasks file for hadoop_hive
- name: Create software directory for Hive
  ansible.builtin.file:
    state: directory
    path: "{{ hive_software_directory }}"
    mode: '0644'

- name: Create Hive workspace directory
  ansible.builtin.file:
    state: directory
    path: "{{ hive_workspace_directory }}"
    mode: '0644'

- name: Ensure .bashrc file exists
  ansible.builtin.copy:
    content: ""
    dest: /home/ubuntu/.bashrc
    force: false
    group: ubuntu
    owner: ubuntu
    mode: '0600'

- name: Download Hive software and extract it to the specified Location
  ansible.builtin.unarchive:
    src: "{{ hive_software_download_url }}"
    dest: "{{ hive_software_directory }}"
    remote_src: true

- name: Make Environmental Variables Permanent after reboot
  ansible.builtin.blockinfile:
    path: /home/ubuntu/.bashrc
    content: |
      export HIVE_HOME={{ hive_software_directory }}{{ hive_software_version }}/
      export PATH={{ hive_software_directory }}{{ hive_software_version }}/bin/:$PATH
